name = "Antistasi Ultimate Community Server Addon";
author = "Silence";
description = "";
tooltip = "AUC Server";
tooltipOwned = "AUC Server";
overview = "A serverside addon for Antistasi Ultimate Community";
actionName = "GitHub";
action = "https://github.com/SilenceIsFatto/auc_server";
hideName = 0;
hidePicture = 0;
dlcColor[] = {1, 0, 0, 1};
logo = "\z\auc\addons\core\logo_ca.paa"; // Logo displayed in the main menu
logoOver = "\z\auc\addons\core\logo_ca.paa"; // When the mouse is over, in the main menu
picture = "\z\auc\addons\core\logo_ca.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
logoSmall = "\z\auc\addons\core\logo_ca.paa"; // Display in creative lists, next to the entities added by the mod